spring:
  application:
    name: jiangyang-module-iot-plugin-emqx

jiangyang:
  iot:
    plugin:
      common:
        upstream-url: http://127.0.0.1:48080
        downstream-port: 8100
        plugin-key: jiangyang-module-iot-plugin-emqx
      emqx:
        mqtt-host: 127.0.0.1
        mqtt-port: 1883
        mqtt-ssl: false
        mqtt-username: jiangyang
        mqtt-password: 123456
        mqtt-topics:
          - "/sys/#"
        auth-port: 8101
