spring:
  data:
    redis:
      host: 8.133.246.113 # Redis服务器地址
      port: 6379 # Redis端口号
      password: 5z25u2sk # Redis密码
      database: 1 # 使用的数据库索引
      timeout: 5000 # 连接超时时间（毫秒）
      lettuce: # 使用Lettuce客户端的配置
        pool:
          max-active: 8 # 连接池最大连接数
          max-idle: 8 # 连接池最大空闲连接数
          min-idle: 0 # 连接池最小空闲连接数
          max-wait: -1 # 连接池最大阻塞等待时间（负值表示没有限制）
      client-type: lettuce # 明确指定使用lettuce客户端
      connect-timeout: 5000 # 连接超时时间 